name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/master
        submodules : recursive
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
    - name: Init
      run: |
        choco install -y ninja
        refreshenv
    - name: Compile luamake
      run: |
        git clone https://github.com/actboy168/luamake.git
        cd luamake
        git submodule update --init --recursive
        tools\ninja -f ninja\msvc.ninja
        cd ..
    - name: Compile
      run: |
        .\luamake\luamake
        .\luamake\luamake lua make\make.lua ci

